def atrribute_error():
    x = 10
    x.append(3)
    return x
#atrribute_error()